name: Build message

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Build the things
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - run: mvn -B package --file pom.xml # Build
      - run: mkdir staging && cp target/*.jar staging # Move files
      - uses: actions/upload-artifact@v2 # Upload
        with:
          name: message
          path: staging/*
          retention-days: 10 # Delete artifacts after 10 days